name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools pip-audit

      - name: Update requirements
        run: |
          # Create requirements.in if it doesn't exist
          if [ ! -f requirements.in ]; then
            cp requirements.txt requirements.in
          fi

          # Update dependencies
          pip-compile --upgrade requirements.in

      - name: Check for security vulnerabilities
        run: |
          pip-audit --requirement requirements.txt --format=json --output=security-report.json || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔄 Update dependencies"
          title: "🔄 Weekly dependency update"
          body: |
            ## Automated Dependency Update

            This PR updates all dependencies to their latest compatible versions.

            ### Changes
            - Updated Python packages in `requirements.txt`
            - Security audit results attached

            ### Security Check
            Please review the security audit results before merging.

            **Auto-generated by GitHub Actions**
          branch: dependency-updates
          delete-branch: true
          labels: dependencies,automated
